# Generated by Django 2.2.5 on 2019-10-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nome', 'valor')},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('nome',), 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ('data_inicio', 'data_termino')},
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(verbose_name='Data de término'),
        ),
    ]
